spring:
  application:
    name: adg-rule
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  rule:
    #远程规则
    remote:
      - 'https://raw.githubusercontent.com/damengzhu/banad/main/dnslist.txt' #X浏览器酷安@大萌主维护的专门针对手机端盗版网站广告的拦截规则
      - 'https://raw.githubusercontent.com/Cats-Team/AdRules/main/hosts.txt' #Cats-Team
      - 'https://raw.githubusercontent.com/banbendalao/ADgk/master/kill-baidu-ad.txt' #去除百家号
      - 'https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt' #ADGK
      - 'https://easylist-downloads.adblockplus.org/easyprivacy.txt' #easyprivacy隐私规则
      - 'https://raw.githubusercontent.com/Noyllopa/NoAppDownload/master/NoAppDownload.txt' #去app下载提示
      - 'https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.adblock' #d3ward规则
      - 'https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts' #yhost
      - 'https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts' #ad-war
    #本地规则
    local: #本地规则请将文件移动到项目路径rule目录中
      - 'mylist.txt'
  output:
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt:    #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      adgh.txt:
        - DOMAIN
        - REGEX
#        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
